### ISSUE TITLE
EPIC: Migrate to the vuejs frontend

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall_activerecord#22]
- [ ] inspecjs middleware
- [ ] vuejs components built from https://bit.dev/
- [ ] update layouts to new designs
- [ ] update user / admin screens

**Comment by aaronlippold** [comment]
Please add to this for feedback, features, etc.
